---
- hosts: ubuntu
  sudo: yes
  tasks:
      - name: Add the Go-CD repo
        apt_repository: repo='deb http://download.go.cd/gocd-deb/ /' state=present 
      - name: Install JDK 7
        apt: name=openjdk-7-jdk state=latest update_cache=yes 
        # Need to force apt because source is untrusted
      - name: Install Go-CD server
        apt: name=go-server state=latest force=yes
        notify:
            - Start Go-CD server
  handlers:
      - name: Start Go-CD server
        service: name=go-server state=started
