---
# Install the go-server
- 
  hosts: go_server
  sudo: yes
  roles:
      - go_server

# Install the go-agents
- 
  hosts: go_agents
  sudo: yes
  roles:
      - { 
            role: go_agent, 
            # First element of go_server group
            go_server_hostname: "{{ hostvars[groups['go_server'][0]]['ansible_default_ipv4']['address'] }}"
        }
