---
- hosts: ubuntu
  sudo: yes
  vars:
      go_server_hostname: "127.0.0.1"
  tasks:

      - name: Add the Go-CD repo
        apt_repository: repo='deb http://download.go.cd/gocd-deb/ /' state=present 
            
      - name: Install JDK 7
        apt: name=openjdk-7-jdk state=latest update_cache=yes 

        # Need to force apt because source is untrusted
      - name: Install Go-CD agent 
        apt: name=go-agent state=latest force=yes
        notify:
            - Restart Go-CD agent
      - name: Replace the GO_SERVER parameter
        replace: dest=/etc/default/go-agent regexp='GO_SERVER=(.*)$' replace='GO_SERVER={{ go_server_hostname }}'

  handlers:
      - name: Restart Go-CD agent 
        service: name=go-agent state=restarted
