---
- name: Add the apt repository for nginx
  apt_repository: repo="ppa:nginx/stable" update_cache=yes

- name: Install nginx
  apt: name=nginx state=present

- name: Remove default site
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify:
      - Restart nginx

- name: Configure a site
  copy: src={{ site_file }} dest=/etc/nginx/sites-available/{{ site_file|basename }}
  when: site_file is defined

- name: Enable a site
  file: src=/etc/nginx/sites-available/{{ site_file|basename }} dest=/etc/nginx/sites-enabled/{{ site_file|basename }} state=link
  when: site_file is defined
  notify:
      - Restart nginx

- name: Copy the ssl folder
  copy: src={{ ssl_folder }} dest=/etc/nginx/ssl/
  when: ssl_folder is defined
  notify:
      - Restart nginx

- name: Start nginx
  service: name=nginx state=started
